PROGS = logic-analyzer.c
# STAFF_OBJS += $(CS140E_2026_PATH)/libpi/staff-objs/staff-sw-uart.o
COMMON_SRC = $(CS140E_2026_PATH)/libpi/src/sw-uart.c
STAFF_OBJS += $(CS140E_2026_PATH)/libpi/staff-objs/interrupts-asm.o
STAFF_OBJS += $(CS140E_2026_PATH)/libpi/staff-objs/interrupts-vec-asm.o

# automatically run the code
RUN = 0

# if you need to override the install
BOOTLOADER = my-install

include $(CS140E_2026_PATH)/libpi/mk/Makefile.robust-v2
