# need the makefile to give an error if this doesn't exist
PROGS := 0-syscall.c 1-syscall.c
COMMON_SRC := syscall-asm.S  interrupts-asm.S
#1-syscall.c
# uncomment if you want it to automatically run.
# RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install

include $(CS140E_2026_PATH)/libpi/mk/Makefile.robust-v2
