BOOTLOADER = my-install

PROGS := tests/1-test-basic-tutorial.c
PROGS += tests/1-test-one-addr.c
PROGS += tests/1-test-two-addr.c
PROGS += tests/2-test-lookup.c
PROGS += tests/2-test-procmap.c
# PROGS += tests/4-test-part4.c


# your code will go here.
COMMON_SRC = pinned-vm.c

O = $(CS140E_2026_PATH)/libpi
STAFF_OBJS += $(O)/staff-objs/staff-full-except.o
STAFF_OBJS += $(O)/staff-objs/staff-full-except-asm.o
STAFF_OBJS += $(O)/staff-objs/staff-switchto-asm.o
STAFF_OBJS += staff-mmu-asm.o  
STAFF_OBJS += staff-mmu-except.o  
STAFF_OBJS += staff-mmu.o  
# STAFF_OBJS += staff-pinned-vm.o
STAFF_OBJS += $(O)/staff-objs/staff-kmalloc.o

# define this if you need to give the device for your pi
TTYUSB = 

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

include $(CS140E_2026_PATH)/libpi/mk/Makefile.robust-v3

clean::
	make -C tests clean
